services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: [ "uvicorn", "src.ops_solution:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    dns:
      - 8.8.8.8

  extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extractor
    command: [ "python", "src/email-extract-app.py" ]
    env_file: .env
    restart: always
    dns:
      - 8.8.8.8

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    command: [ "python", "src/remainder_scheduler.py" ]
    env_file: .env
    restart: always
    dns:
      - 8.8.8.8

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer
    command: [ "python", "src/error-solution-create.py" ]
    env_file: .env
    restart: always
    dns:
      - 8.8.8.8
